import { StyleSheet, StatusBar, Platform } from 'react-native';

import { COMMON_STYLE, STYLES } from '@themes';
import { Responsive } from '@helpers';

export const style = theme =>
  StyleSheet.create({
    ...COMMON_STYLE,
    ...STYLES,
    screenBG: {
      flex: 1,
    },
    ScrollView: {
      flexGrow: 1,
    },
    header: {
      height: Platform.OS === 'ios' ? 55 : StatusBar.currentHeight + 65,
      paddingHorizontal: 15,
      // borderBottomWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      flexDirection: 'row',
      alignItems: 'flex-end',
      paddingBottom: Responsive.getWidth(3),
    },
    headerLeft: {
      width: 30,
    },
    headerCenter: {
      flex: 1,
      flexDirection: 'row',
      // alignItems: 'center',
      justifyContent: 'center',
    },
    headerRight: {
      position: 'relative',
      width: 50,
      alignItems: 'flex-end',
      top: 5,
    },
    headerTitleView: {
      flex: 1,
      justifyContent: 'center',
      // backgroundColor: 'red',
    },
    headerTitle: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BOLD'),
    },
    eventScroll: {
      // paddingHorizontal: Responsive.getWidth(6),
    },
    headerIcon: {
      ...STYLES.imageStyle(6),
    },
    headerLeftIcon: {
      ...STYLES.textStyle(20, theme?.colors?.RED_500),
      marginLeft: -5,
    },
    headerRightImgWrap: {
      width: Responsive.getWidth(9),
      height: Responsive.getWidth(9),
      borderRadius: 75,
      overflow: 'hidden',
    },
    headerRightImg: {
      width: '100%',
      height: '100%',
    },
    safeAreaStyle: {
      width: '100%',
      height: '100%',
      backgroundColor: theme?.colors?.DARK_OPACITY,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      position: 'absolute',
    },
    alertBoxStyle: {
      width: Responsive.getWidth(100),
      maxHeight: Responsive.getHeight(55),
      borderRadius: Responsive.getWidth(3),
      backgroundColor: theme?.colors?.WHITE,
    },
    closeButtonStyle: {
      width: Responsive.getWidth(8),
      height: Responsive.getWidth(8),
      alignSelf: 'flex-end',
      margin: Responsive.getWidth(2),
      backgroundColor: theme?.colors?.TRANSPARENT,
    },
    button: {
      paddingHorizontal: 20,
      borderRadius: 30,
      backgroundColor: theme?.colors?.RED_500,
    },
    closeIconStyle: {
      width: Responsive.getWidth(4),
      height: Responsive.getWidth(4),
    },
    profileBtnViewStyle: {
      marginVertical: Responsive.getHeight(2),
      alignItems: 'center',
      justifyContent: 'space-evenly',
      height: 150,
    },
    chatIconBtn: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    chatIcon: {
      ...STYLES.textStyle(18, '#484850'),
      marginHorizontal: Responsive.getWidth(3),
    },
    chatFooter: {
      // position: 'absolute',
      // bottom: 0,
      width: '100%',
      paddingHorizontal: 15,
      borderTopWidth: 1,
      borderColor: theme?.colors?.GRAY_800,
      // backgroundColor: theme?.colors?.GRAY_1000,
      paddingBottom: Platform.OS === 'ios' ? 0 : 10,
    },
    inputContainer: {},
    msgInput: {
      ...STYLES.textStyle(14, theme?.colors?.WHITE, 'BASE'),
      height: 'auto',
      minHeight: 50,
      maxHeight: 100,
      paddingTop: 10,
    },
    footerIconRow: {
      height: 50,
      flexDirection: 'row',
      alignItems: 'center',
    },
    footerIconColLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    footerIconColRight: {
      width: 100,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
    },
    footerIconBtn: {
      flex: 1,
    },
    footerIcon: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_100),
    },
    footerLeftIconBtn: {},
    footerLeftIcon: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_100),
    },
    noMsgContainer: {
      padding: 15,
      marginTop: Responsive.getWidth(10),
    },
    alertTitleStyle: {
      ...COMMON_STYLE.textStyle(16, theme?.colors?.BLACK, 'BOLD', 'center'),
    },
    descriptionStyle: {
      ...COMMON_STYLE.textStyle(14, theme?.colors?.DARK_GRAY, undefined, 'center'),
      marginHorizontal: Responsive.getWidth(2),
      marginVertical: Responsive.getHeight(1),
    },
    profileBtnViewStyle: {
      marginVertical: Responsive.getHeight(2),
      alignItems: 'center',
      justifyContent: 'space-evenly',
      height: 150,
    },
    noMsgTxt: {
      ...STYLES.textStyle(14, theme?.colors?.GRAY_300, 'BASE', 'center'),
      lineHeight: 24,
      width: Responsive.getWidth(80),
      alignSelf: 'center',
    },

    msgContainer: {
      paddingHorizontal: 10,
      flex: 1,
      // // flexDirection: 'column-reverse',
    },
    msgContainerLeft: {
      width: Responsive.getWidth(85),
      marginBottom: Responsive.getWidth(5),
      // backgroundColor: theme?.colors?.RED_500
    },
    msgContainerRight: {
      width: Responsive.getWidth(70),
      marginBottom: Responsive.getWidth(5),
      marginLeft: 'auto',
      marginRight: 0,
    },
    msgRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
    },
    senderImgWrap: {
      width: Responsive.getWidth(8),
      height: Responsive.getWidth(8),
      borderRadius: 75,
      marginRight: Responsive.getWidth(1),
      // overflow: 'hidden',
      position: 'relative',
    },
    replyBtnLine: {
      width: 17,
      height: 42,
      position: 'absolute',
      top: Responsive.getWidth(9),
      left: '50%',
    },
    msgRowReplyView: {
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      paddingTop: Responsive.getWidth(3),
      borderRadius: 10,
      // backgroundColor: theme?.colors?.GRAY_800,
      backgroundColor: 'rgba(255,255,255,0.2)',
      marginBottom: Responsive.getWidth(3),
    },
    replyLine: {
      width: Responsive.getWidth(3),
      height: '100%',
      borderLeftWidth: 1,
      borderBottomWidth: 1,
      borderColor: theme?.colors?.GRAY_300,
      borderBottomLeftRadius: 8,
      position: 'absolute',
      top: -Responsive.getWidth(9),
      left: Responsive.getWidth(4),
    },
    replyLineRight: {
      width: 12,
      height: '100%',
      borderRightWidth: 1,
      borderBottomWidth: 1,
      borderColor: 'rgba(255,255,255,0.2)',
      borderBottomRightRadius: 8,
      position: 'absolute',
      top: -Responsive.getWidth(5),
      right: Responsive.getWidth(2),
      zIndex: 150,
    },
    userImg: {
      width: '100%',
      height: '100%',
      borderRadius: 75,
    },
    closeIconStyle: {
      width: Responsive.getWidth(4),
      height: Responsive.getWidth(4),
    },
    msgTxtBox: {
      position: 'relative',
      flex: 1,
      width: Responsive.getWidth(60),
      marginHorizontal: Responsive.getWidth(3),
    },
    msgTxtBoxLeft: {
      position: 'relative',
      flex: 1,
      width: Responsive.getWidth(60),
      marginLeft: Responsive.getWidth(3),
      marginRight: Responsive.getWidth(2),
    },
    msgTxtBoxRight: {
      position: 'relative',
      flex: 1,
      width: Responsive.getWidth(60),
      marginLeft: Responsive.getWidth(2),
      marginRight: Responsive.getWidth(3),
    },
    msgTxtBox2: {
      position: 'relative',
      marginHorizontal: Responsive.getWidth(3),
    },
    msgTxtBoxLeft2: {
      position: 'relative',
      marginLeft: Responsive.getWidth(3),
      marginRight: Responsive.getWidth(2),
    },
    msgTxtBoxRight2: {
      position: 'relative',
      marginLeft: Responsive.getWidth(2),
      marginRight: Responsive.getWidth(3),
    },
    msgTimeTxt: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_200, 'BASE', 'left'),
      marginBottom: 5,
    },
    msgTimeTxtRight: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_200, 'BASE', 'right'),
      marginBottom: 5,
    },
    typeMsgTxtLeftView: {
      borderWidth: 1,
      backgroundColor: theme?.colors?.RED_500,
      borderColor: theme?.colors?.RED_500,
      borderRadius: 10,
      padding: 10,
    },
    typeMsgTxtLeft: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      lineHeight: 20,
    },
    typeMsgTxt: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      lineHeight: 20,
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      padding: 10,
      backgroundColor: 'rgba(255,255,255,0.2)',
      overflow: 'hidden',
    },
    typeMsgInnerTxt2: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      fontSize: 14,
      lineHeight: 20,
    },
    typeMsgInnerTxt1: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      backgroundColor: 'rgba(225, 225, 225, 0.2)',
      fontSize: 14,
      lineHeight: 20,
      borderRadius: 8,
      padding: 10,
      marginBottom: 5,
      overflow: 'hidden',
    },
    typeMsgInnerTxt1Left: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      backgroundColor: 'rgba(207, 186, 163, 0.3)',
      fontSize: 14,
      lineHeight: 20,
      borderRadius: 8,
      padding: 10,
      marginBottom: 5,
      overflow: 'hidden',
    },
    typeMsgTxtInnerLeftView: {
      backgroundColor: theme?.colors?.RED_500,
      // borderWidth: 1,
      // borderColor: theme?.colors?.RED_500,
      borderRadius: 10,
      padding: 10,
    },
    typeMsgTxtIn: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      lineHeight: 20,
    },
    typeMsgReplyTxtIn: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      lineHeight: 20,
      marginTop: Responsive.getWidth(2.3),
      marginBottom: Responsive.getWidth(2),
    },
    shareImgView: {
      flex: 1,
      height: Responsive.getHeight(18),
      borderRadius: 10,
      overflow: 'hidden',
    },
    shareImg: {
      width: '100%',
      height: '100%',
    },
    replyBtnRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: Responsive.getHeight(6),
    },
    replyBtn: {
      position: 'relative',
      top: -Responsive.getHeight(0.8),
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme?.colors?.GRAY_300,
      borderRadius: 30,
      marginLeft: Responsive.getHeight(6),
      paddingHorizontal: Responsive.getHeight(1),
      borderWidth: 3,
      borderColor: theme?.colors?.GRAY_1000,
      zIndex: 151,
    },
    replyBtnIcon: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_100, 'BASE', 'left'),
    },
    replyBtnTxt: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_100, 'BASE', 'left'),
      // marginTop: 5,
      // marginRight: 15,
      marginLeft: Responsive.getHeight(0.5),
    },
    msgLikeViewLeft: {
      position: 'absolute',
      right: Responsive.getHeight(1),
      bottom: -Responsive.getHeight(2),
      backgroundColor: '#28283E',
      borderWidth: 2,
      borderColor: '#03021D',
      borderRadius: 30,
      paddingVertical: Responsive.getWidth(0.3),
      paddingHorizontal: Responsive.getWidth(3),
      zIndex: 1051,
    },
    msgLikeViewRight: {
      position: 'absolute',
      left: Responsive.getHeight(1),
      bottom: -Responsive.getHeight(2),
      backgroundColor: '#28283E',
      borderWidth: 2,
      borderColor: '#03021D',
      borderRadius: 30,
      paddingVertical: Responsive.getWidth(0.3),
      paddingHorizontal: Responsive.getWidth(3),
      zIndex: 1051,
    },
    msgLikeBtn: {
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      width: Responsive.getHeight(2),
      height: Responsive.getHeight(2),
      // backgroundColor: 'yellow',
      zIndex: 1,
    },
    // msgLikeBtn: {
    //   flexDirection: 'row',
    //   alignItems: 'center',
    //   borderWidth: 1,
    //   borderColor: theme?.colors?.GRAY_800,
    //   borderRadius: 10,
    //   // paddingHorizontal: 8,
    //   justifyContent: 'center',
    //   paddingVertical: 2,
    //   // marginBottom: 20,
    //   minWidth: 40,
    //   marginBottom: 3,
    // },
    msgLikeBtn1: {
      flexDirection: 'row',
      alignItems: 'center',
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      // paddingHorizontal: 8,
      justifyContent: 'flex-end',
      paddingVertical: 2,
      // marginBottom: 20,
      minWidth: 40,
      marginBottom: 3,
    },
    msgLikeBtn2: {
      flexDirection: 'row',
      alignItems: 'center',
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      // paddingHorizontal: 8,
      justifyContent: 'flex-start',
      paddingVertical: 2,
      // marginBottom: 20,
      minWidth: 40,
      marginBottom: 3,
    },
    likeIcon: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_300),
      position: 'absolute',
      zIndex: 5,
      marginLeft: -Responsive.getWidth(1),
    },
    likeIcon2: {
      ...STYLES.textStyle(12, 'red'),
      position: 'absolute',
      zIndex: 5,
      marginLeft: -Responsive.getWidth(1),
      shadowColor: '#000',
      shadowOffset: {
        width: -1,
        height: -1,
      },
      shadowOpacity: 1,
      shadowRadius: 1,
      elevation: 10,
    },
    likeCountTxt: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_50),
      position: 'absolute',
      zIndex: 6,
      marginLeft: Responsive.getWidth(2),
    },
    replyLeftView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 15,
      width: Responsive.getWidth(82),
      marginLeft: 'auto',
    },
    replyImgWrap: {
      width: Responsive.getWidth(7),
      height: Responsive.getWidth(7),
      borderRadius: 75,
    },
    replyViewContent: {
      paddingLeft: Responsive.getWidth(2),
    },
    replyNameTxt: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_300),
    },
    replyNameInnerTxt: {
      ...STYLES.textStyle(11, theme?.colors?.WHITE),
    },
    replyTxt2: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_100),
      marginTop: 3,
    },
    eventView: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.2)',
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      // borderColor: 'rgba(255,255,255,0.2)',
      borderRadius: 10,
      padding: 10,
    },
    eventDateView: {
      width: Responsive.getWidth(15),
      height: Responsive.getWidth(15),
      borderRadius: 10,
      backgroundColor: 'rgba(255,255,255,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventDetail: {
      flex: 1,
      paddingLeft: 10,
    },
    eventDateTxt1: {
      ...STYLES.textStyle(12, theme?.colors?.BLACK, 'BASE'),
      textTransform: 'uppercase',
    },
    eventDateTxt2: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_300, 'BOLD'),
      marginTop: 3,
    },
    eventTitle2: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE'),
    },
    eventSubjectTxt: {
      ...STYLES.textStyle(11, theme?.colors?.GRAY_100, 'BASE'),
      marginTop: 3,
    },
    eventDate: {
      ...STYLES.textStyle(11, theme?.colors?.GRAY_100, 'BASE'),
      marginTop: 3,
    },
    eventViewLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme?.colors?.RED_500,
      borderRadius: 10,
      padding: 10,
    },
    eventSubjectTxtLeft: {
      ...STYLES.textStyle(11, theme?.colors?.WHITE, 'BASE'),
      marginTop: 3,
    },
    eventDateLeft: {
      ...STYLES.textStyle(11, theme?.colors?.WHITE, 'BASE'),
      marginTop: 3,
    },
    optionView: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      padding: 10,
    },
    optionQuestionTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
    },
    optionRow: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(9),
      borderRadius: 8,
      backgroundColor: theme?.colors?.GRAY_800,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      marginTop: 8,
      overflow: 'hidden',
    },
    optionRowTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
      zIndex: 1,
    },
    optionRowTxtIcon: {
      ...STYLES.textStyle(14, theme?.colors?.GRAY_50),
    },
    optionProgress: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '0%',
      height: '100%',
      backgroundColor: theme?.colors?.RED_500,
    },
    tabHeader: {
      flexDirection: 'row',
      borderBottomWidth: 0,
      borderColor: 'rgba(0,0,0,0.08)',
      width: '100%',
      marginTop: 10,
    },
    tabStyle: {
      flex: 1,
      paddingHorizontal: Responsive.getWidth(10),
      paddingVertical: Responsive.getWidth(15),
      color: theme?.colors?.WHITE,
    },
    selectTabStyle: {
      borderBottomWidth: 3,
      borderColor: theme?.colors?.RED_500,
    },
    tabTextStyle: {
      textAlign: 'center',
      color: '#020108',
      fontSize: Responsive.getWidth(18),
    },
    selectTabTextStyle: {
      color: '#222B45',
    },
    holdBtn: {
      width: Responsive.getWidth(10),
      // height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      // backgroundColor: theme?.colors?.RED_500,
      // borderTopLeftRadius: Responsive.getWidth(2),
      // borderTopRightRadius: Responsive.getWidth(2),
    },
    holdBtnIcon: {
      fontSize: Responsive.getWidth(5),
      color: theme?.colors?.WHITE,
    },
    holdBtnImg: {
      width: Responsive.getWidth(5),
      height: Responsive.getWidth(5),
    },
    titleStyle: {
      textTransform: 'none',
      ...STYLES.textStyle(14, theme?.colors?.GRAY_300, 'BOLD', 'center'),
    },
    titleActiveStyle: {
      textTransform: 'none',
      ...STYLES.textStyle(14, theme?.colors?.RED_500, 'BOLD', 'center'),
    },
    sidenotHiddenRow: {
      height: '84%',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      backgroundColor: theme?.colors?.BLACK_100,
      borderRadius: 12,
      overflow: 'hidden',
      paddingRight: 20,
    },
    sidenotHiddenCol: {
      width: 100,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sidenotHiddenColIcon: {
      ...STYLES.textStyle(18, theme?.colors?.WHITE),
    },
    eventItem: {
      borderRadius: Responsive.getWidth(6),
      overflow: 'hidden',
      backgroundColor: theme?.colors?.GRAY_900,
      // borderWidth: 1,
      // borderColor: 'rgba(207, 186, 163, 0.24)',
      marginBottom: Responsive.getWidth(5),
      minHeight: Responsive.getWidth(40),
      marginBottom: Responsive.getWidth(5),
    },
    eventImageView: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(54),
    },
    eventImage: {
      width: '100%',
      height: '100%',
    },
    gradientLayer: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0,0,0,0.3)',
      opacity: 0.5,
    },
    eventContent: {
      position: 'absolute',
      bottom: 0,
      padding: Responsive.getWidth(6),
      width: '100%',
      height: '100%',
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    eventContentRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    smallBtn: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      height: Responsive.getWidth(9),
      paddingHorizontal: Responsive.getWidth(3),
      borderRadius: Responsive.getWidth(9),
      justifyContent: 'center',
      alignItems: 'center',
      width: 'auto',
      alignSelf: 'flex-end',
    },
    smallBtnText: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'center'),
    },
    eventTitle: {
      ...STYLES.textStyle(20, theme?.colors?.WHITE, 'BASE', 'left'),
      marginBottom: 2,
      textShadowColor: 'rgba(0, 0, 0, 0.50)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 10,
    },
    eventText: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE', 'left'),
      opacity: 0.8,
      textShadowColor: 'rgba(0, 0, 0, 0.50)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 10,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Responsive.getWidth(6),
    },
    modalView: {
      width: '100%',
      backgroundColor: 'rgba(24, 24, 24, 0.7)',
      padding: Responsive.getWidth(5),
      borderRadius: Responsive.getWidth(4),
    },
    modalImageView: {
      width: Responsive.getWidth(35),
      height: Responsive.getWidth(35),
      backgroundColor: '#ECECEC',
      alignSelf: 'center',
      marginBottom: 35,
    },
    modalTitle: {
      ...COMMON_STYLE.textStyle(16, theme?.colors?.DARK_GRAY, 'BOLD', 'center'),
      marginBottom: 6,
    },
    modalText: {
      ...COMMON_STYLE.textStyle(13, theme?.colors?.WHITE, 'BASE', 'center'),
      marginBottom: 15,
      marginTop: 10,
    },
    modalButtonText: {
      ...COMMON_STYLE.textStyle(16, theme?.colors?.BLACK, 'BOLD', 'center'),
      marginTop: 20,
    },
    cellSeprator: {
      borderWidth: 0.3,
      borderColor: theme?.colors?.INPUT_GRAY_COLOR,
    },
    ListItemAccordion: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    checkboxItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Responsive.getWidth(5),
    },
    checkboxBody: {
      flex: 1,
      paddingHorizontal: Responsive.getWidth(8),
    },
    checkboxTextStyle: {
      color: theme?.colors?.WHITE,
      fontSize: Responsive.getWidth(16),
    },
    sectionHeaderTitle: {
      ...STYLES.textStyle(15, theme?.colors?.RED_500, 'BOLD', 'left'),
      marginTop: Responsive.getWidth(2),
    },
    modalContainer2: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.8)',
    },
    modalView2: {
      flex: 1,
      width: '100%',
      padding: Responsive.getWidth(6),
    },
    groupModalTitle: {
      ...STYLES.textStyle(16, theme?.colors?.WHITE, 'BASE', 'center'),
    },
    groupModalFlatList: {
      flex: 1,
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalTitleView: {
      paddingVertical: 20,
    },
    modalTitleText: {
      ...STYLES.textStyle(16, theme?.colors?.WHITE, 'BASE', 'center'),
    },
    titleStyle2: {
      textTransform: 'none',
      ...STYLES.textStyle(20, theme?.colors?.WHITE, 'BOLD', 'center'),
    },
    titleActiveStyle2: {
      textTransform: 'none',
      ...STYLES.textStyle(20, theme?.colors?.RED_500, 'BOLD', 'center'),
    },
    subListIcon2: {
      ...STYLES.imageStyle(6),
      marginRight: Responsive.getWidth(3),
    },
    groupCloseBtn: {},
    groupCloseBtnIcon: {
      ...STYLES.textStyle(40, theme?.colors?.RED_500, 'BOLD', 'center'),
    },
    replyModalTextRow: {
      height: 50,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderColor: theme?.colors?.GRAY_200,
      paddingHorizontal: Responsive.getWidth(3),
    },
    pollTabRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    pollTabBtn: {
      flex: 1,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: 'transparent',
    },
    pollTabBtnActive: {
      flex: 1,
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderBottomWidth: 2,
      borderColor: theme?.colors?.RED_500,
    },
    pollTabTxt: {
      ...STYLES.textStyle(13, theme?.colors?.GRAY_300, 'BOLD', 'left'),
    },
    pollTabTxtActive: {
      ...STYLES.textStyle(13, theme?.colors?.RED_500, 'BOLD', 'left'),
    },
    pollCard: {
      position: 'relative',
      paddingHorizontal: Responsive.getWidth(3),
      paddingVertical: Responsive.getWidth(2),
      backgroundColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
    },
    pollCardLeft: {
      position: 'relative',
      paddingHorizontal: Responsive.getWidth(3),
      paddingVertical: Responsive.getWidth(2),
      backgroundColor: theme?.colors?.RED_500,
      borderRadius: 10,
    },
    polluserRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderColor: 'rgba(99, 94, 92, 0.24)',
      paddingBottom: Responsive.getWidth(2),
      marginBottom: Responsive.getWidth(2),
    },
    polluserImg: {
      width: Responsive.getWidth(7),
      height: Responsive.getWidth(7),
      borderRadius: 75,
      backgroundColor: theme?.colors?.GRAY_100,
    },
    polluserTxt: {
      flex: 1,
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      paddingLeft: Responsive.getWidth(4),
    },
    polluserTxtInner: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BOLD', 'left'),
    },
    pollCardTitle: {
      ...STYLES.textStyle(14, theme?.colors?.GRAY_100, 'BASE', 'left'),
      marginBottom: Responsive.getWidth(3),
    },
    chatPollCardTitle: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      marginBottom: Responsive.getWidth(3),
    },
    chatPollCardTitleLeft: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      marginBottom: Responsive.getWidth(3),
    },
    pollProgress: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(10),
      borderRadius: 75,
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 8,
      // paddingHorizontal: Responsive.getWidth(3),
      overflow: 'hidden',
      marginBottom: 10,
    },
    pollProgressTxt: {
      ...STYLES.textStyle(12, theme?.colors?.BLACK, 'BASE', 'left'),
      paddingHorizontal: Responsive.getWidth(3),
      zIndex: 1204,
    },
    pollProgressView: {
      position: 'absolute',
      // width: '100%',
      left: 0,
      right: 0,
      height: '100%',
      borderRadius: 8,
      backgroundColor: theme?.colors?.PURPLE,
      zIndex: -1,
    },
    pollVoteRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 3,
    },
    pollVoteTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_300, 'BASE', 'left'),
    },
    pollVoteTxtLeft: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
    },
    pollOptionText: {
      ...STYLES.textStyle(14, theme?.colors?.RED_500, 'BASE', 'left'),
    },
    pollTextProgress: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(10),
      borderRadius: 75,
      backgroundColor: 'rgba(207, 186, 163, 0.1)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 8,
      paddingHorizontal: Responsive.getWidth(3),
      overflow: 'hidden',
      marginBottom: 10,
    },
    pollTextProgressActive: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(10),
      borderRadius: 75,
      backgroundColor: theme?.colors?.RED_500,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 8,
      paddingHorizontal: Responsive.getWidth(3),
      overflow: 'hidden',
      marginBottom: 10,
    },
    eventScroll: {
      // paddingHorizontal: Responsive.getWidth(6),
      // paddingTop: 15,
      paddingTop: 20,
    },
    eventHeaderTitle: {
      ...STYLES.textStyle(12, theme?.colors?.RED_500, 'BOLD'),
      paddingTop: Platform.OS === 'ios' ? 5 : 10,
      paddingBottom: Platform.OS === 'ios' ? 10 : 20,
      borderBottomWidth: 1,
      borderColor: theme?.colors?.GRAY_800,
      paddingRight: 0,
      marginLeft: 0,
      marginBottom: Platform.OS === 'ios' ? 0 : 10,
      backgroundColor: theme?.colors?.GRAY_1000,
    },
    eventModalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      // justifyContent: 'center',
      justifyContent: 'flex-end',
      alignItems: 'center',
      padding: Responsive.getWidth(5),
      paddingBottom: Responsive.getWidth(10),
    },
    eventModalView: {
      width: '100%',
      backgroundColor: 'rgba(24, 24, 24, 0.7)',
      // padding: Responsive.getWidth(5),
      borderRadius: Responsive.getWidth(4),
    },
    eventModalImageView: {
      width: Responsive.getWidth(35),
      height: Responsive.getWidth(35),
      backgroundColor: '#ECECEC',
      alignSelf: 'center',
      marginBottom: 35,
    },
    eventModalTitle: {
      ...COMMON_STYLE.textStyle(18, theme?.colors?.DARK_GRAY, 'BASE', 'center'),
      marginBottom: 6,
    },
    eventModalText: {
      ...COMMON_STYLE.textStyle(18, theme?.colors?.WHITE, 'BASE', 'center'),
      paddingVertical: Responsive.getWidth(4),
      // marginBottom: 15,
      // marginTop: 10,
    },
    eventModalButtonText: {
      ...COMMON_STYLE.textStyle(18, theme?.colors?.BLACK, 'BASE', 'center'),
      paddingVertical: Responsive.getWidth(4.5),
      // marginTop: 20,
    },
    eventcellSeprator: {
      borderWidth: 1,
      // borderColor: theme?.colors?.INPUT_GRAY_COLOR,
      borderColor: theme?.colors?.GRAY_200,
      opacity: 0.2,
    },
    atFlatlist: {
      width: '105%',
      height: 200,
      borderBottomWidth: 1,
      borderColor: theme?.colors?.GRAY_400,
      position: 'absolute',
      bottom: 0,
      left: 0,
      backgroundColor: theme?.colors?.GRAY_1000,
      zIndex: 1024,
    },
    atFlatlistInner: {
      // paddingTop: Responsive.getWidth(11),
    },
    atItemRow: {
      width: '100%',
      height: 50,
      paddingHorizontal: Responsive.getWidth(3),
      flexDirection: 'row',
      alignItems: 'center',
      borderTopWidth: 1,
      borderColor: theme?.colors?.GRAY_400,
    },
    atUserImg: {
      width: Responsive.getWidth(8),
      height: Responsive.getWidth(8),
      borderRadius: 75,
      backgroundColor: theme?.colors?.RED_500,
    },
    atUserName: {
      flex: 1,
      ...COMMON_STYLE.textStyle(12, theme?.colors?.GRAY_50, 'BASE', 'left'),
      paddingLeft: Responsive.getWidth(3),
    },
    myAnswerIcon: {
      marginLeft: 5,
      height: 20,
      width: 20,
      zIndex: 1,
      tintColor: theme?.colors?.WHITE,
    },
    groupWipeoutBtnViewRight: {
      backgroundColor: theme?.colors?.INPUT_BG,
      alignSelf: 'flex-end',
      width: '100%',
      height: Responsive.getWidth(10),
      marginBottom: Responsive.getWidth(5.5),
      justifyContent: 'center',
      alignItems: 'center',
      // borderTopRightRadius: 10,
      // borderBottomRightRadius: 10,
    },
    groupWipeoutBtnViewLeft: {
      backgroundColor: theme?.colors?.INPUT_BG,
      alignSelf: 'flex-end',
      width: '100%',
      height: Responsive.getWidth(10),
      marginBottom: Responsive.getWidth(11),
      justifyContent: 'center',
      alignItems: 'center',
      // borderTopLeftRadius: 10,
      // borderBottomLeftRadius: 10,
    },

    radiusRight: {
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
    },
    radiusLeft: {
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
    },
    headerText: {
      ...COMMON_STYLE.textStyle(11, theme?.colors?.GRAY_200, 'BASE', 'center'),
      marginRight: 10,
    },
    selectedHeaderText: {
      ...COMMON_STYLE.textStyle(15, theme?.colors?.WHITE, 'BOLD', 'center'),
      marginRight: 10,
    },
    addToCalenderModal: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      // justifyContent: 'center',
      justifyContent: 'flex-end',
      alignItems: 'center',
      padding: Responsive.getWidth(5),
      paddingBottom: Responsive.getWidth(10),
    },
    calendarView: {
      width: '100%',
      backgroundColor: 'rgba(24, 24, 24, 0.7)',
      // padding: Responsive.getWidth(5),
      borderRadius: Responsive.getWidth(4),
    },
    reportModalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    reportModalView: {
      width: '100%',
      padding: Responsive.getWidth(5),
      backgroundColor: theme?.colors?.GRAY_800,
      borderTopLeftRadius: Responsive.getWidth(4),
      borderTopRightRadius: Responsive.getWidth(4),
      paddingBottom: Responsive.getWidth(10),
    },
    modalTopLine: {
      width: Responsive.getWidth(18),
      height: Responsive.getWidth(1),
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      borderRadius: Responsive.getWidth(10),
      marginBottom: Responsive.getWidth(5),
      alignSelf: 'center',
      marginTop: -Responsive.getWidth(3),
    },
    modalTitle2: {
      ...COMMON_STYLE.textStyle(16, theme?.colors?.WHITE, 'BOLD', 'center'),
      marginBottom: Responsive.getWidth(5),
    },
    inputLebal: {
      ...COMMON_STYLE.textStyle(13, theme?.colors?.GRAY_100, 'BOLD'),
      marginBottom: Responsive.getWidth(1),
      paddingLeft: Responsive.getWidth(3),
    },
    reportInput: {
      width: '100%',
      height: Responsive.getWidth(14),
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      paddingHorizontal: Responsive.getWidth(3),
      borderRadius: Responsive.getWidth(4),
      ...COMMON_STYLE.textStyle(14, theme?.colors?.WHITE, 'BASE'),
    },
    calendarTextStyle: {
      ...COMMON_STYLE.textStyle(14, theme?.colors?.GRAY_100, 'BASE'),
    },
    todayBackgroundColor: {
      backgroundColor: theme?.colors?.RED_500,
    },
    todayTextStyle: {
      ...COMMON_STYLE.textStyle(14, theme?.colors?.WHITE, 'BASE'),
    },
    monthTitleStyle: {
      ...COMMON_STYLE.textStyle(14, theme?.colors?.RED_500, 'BOLD'),
    },
    monthTitleStyle: {
      ...COMMON_STYLE.textStyle(14, theme?.colors?.RED_500, 'BOLD'),
    },
    arrowStyle: {
      ...COMMON_STYLE.imageStyle(3, theme?.colors?.RED_500),
    },
    userModalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'flex-end',
      alignItems: 'center',
    },
    modalBodyclose: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    userModalView: {
      width: '100%',
      backgroundColor: theme?.colors?.GRAY_900,
      padding: Responsive.getWidth(8),
      paddingHorizontal: Responsive.getWidth(6),
      // borderRadius: Responsive.getWidth(4),
      borderTopLeftRadius: Responsive.getWidth(5),
      borderTopRightRadius: Responsive.getWidth(5),
    },
    userModalImageView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 35,
    },
    modalImageViewBody: {
      flex: 1,
      paddingRight: Responsive.getWidth(5),
    },
    userName: {
      ...STYLES.textStyle(20, theme?.colors?.GRAY_50, 'BOLD', 'left'),
      marginBottom: 10,
    },
    contatText: {
      ...COMMON_STYLE.textStyle(12, theme?.colors?.GRAY_200, 'BASE', 'left'),
    },
    connectionTxt1: {
      ...STYLES.textStyle(16, theme?.colors?.GRAY_50, 'BOLD', 'center'),
      marginBottom: Responsive.getHeight(0.5),
    },
    connectionTxt2: {
      ...STYLES.textStyle(9, theme?.colors?.GRAY_50, 'BASE', 'center'),
      opacity: 0.7,
    },
    userProfileImage: {
      width: Responsive.getWidth(30),
      height: Responsive.getWidth(30),
      borderRadius: 75,
      resizeMode: 'cover',
    },
    sendButton: {
      backgroundColor: theme?.colors?.RED_500,
      padding: Responsive.getWidth(3),
      paddingHorizontal: Responsive.getHeight(4),
      borderRadius: 30,
      marginTop: Responsive.getHeight(2),
      alignSelf: 'center',
    },
    sendButtonTxt: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_50, 'BASE', 'center'),
    },
    typeMsgTxtInnerView: {
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      backgroundColor: 'rgba(255,255,255,0.2)',
      padding: 10,
    },
    dmMsgRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingVertical: Responsive.getWidth(3),
    },
    dmMsgTxtView: {
      flex: 1,
      backgroundColor: 'rgba(207, 186, 163, 0.1)',
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 8,
    },
    dmMsgTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_200, 'BASE', 'left'),
    },
    dmMsgIconBtn: {
      marginLeft: 15,
      // ...STYLES.textStyle(11, theme?.colors?.GRAY_100),
      // backgroundColor: theme?.colors?.GRAY_300,
      // width: 20,
      // height: 20,
      // justifyContent: 'center',
      // alignItems: 'center',
      // borderRadius: 75,
      // overflow: 'hidden',
    },
    dmMsgIcon: {
      ...STYLES.imageStyle(5, theme?.colors?.GRAY_100),
    },
  });
