// Reducer keys list to manage reducer data
export const RED_TYPE = {
    API_LOADING: 'loading',
    API_SUCCESS: 'success',
    API_ERROR: 'error',
    NETWORK_STATUS: 'newwork_status',
    USER_DATA: 'userData',
    ALERT_DATA: 'alertData',
    TOAST_DATA: 'toastData',
    NOTIFICATION_LIST: 'notificationList',
    NOTIFICATION_LIST_START: 'notificationListStart',
    NOTIFICATION_LIST_LOAD_MORE: 'notificationListLoadMore',
    NOTIFICATION_READ: 'notificationRead',
    NOTIFICATION_CLEAR_ALL: 'notificationClearAll',
    NOTIFICATION_COUNT: 'notificationCount',
    UPDATE_SETTINGS: 'updateSettings',
    SOUND_NAME: 'soundName',
    SOUND_SIDENOTE_NAME: 'soundSidenoteName',
    THEME_CHANGE: 'selectedTheme',
    SET_IS_ONBOARDING_FINISHED: 'setIsOnBoardingFinished',
  };
  
  export const DASHBOARD_TYPE = {
    SAVE_DASHBOARD: 'saveDashboard',
    UPDATE_DASHBOARD: 'updateDashboard',
    SAVE_TASK_COMPLETE: 'saveTaskComplete',
    SAVE_TASK_LIST: 'saveTaskList',
    SAVE_TASK_DELETE: 'saveTaskDelete',
    SAVE_TASK_LIST_LOAD_MORE: 'saveTaskListLoadMore',
    SAVE_TASK_LIST_COMPLETE: 'saveTaskListComplete',
    SAVE_TASK_ADD: 'saveTaskAdd',
    SAVE_TASK_DETAIL: 'saveTaskDetail',
    SAVE_GROUP_LIST: 'saveGroupList',
    SAVE_GROUP_LIST_LOAD_MORE: 'saveGroupListLoadMore',
    SAVE_TASK_UPDATE: 'saveTaskUpdate',
    TASK_LIST_GROUP_ID: 'taskListGroupId',
    SAVE_USER_ALL: 'saveUserAll',
    SAVE_USER_ALL_LOAD_MORE: 'saveUserAllLoadMore',
    USER_TOKEN: 'userToken',
    CLEAR_TASK: 'clearTask',
    SHOW_MODAL: 'showModalAction',
    SAVE_MY_CONNECTIONS: 'saveMyConnections',
    SAVE_MY_CONNECTIONS_LOAD_MORE: 'saveMyConnectionsLoadMore',
  
    SEND_INVITATION: 'sendInvitatioon',
    SAVE_ITINERARY_DETAILS: 'saveItineraryDetails',
    SAVE_CONTACT: 'getContactNumber',
    UPDATE_CONTACT: 'updateContactStatus',
    SAVE_DRAFT_ITINERARY_LIST: 'getDraftItineraryList',
    SAVE_ITINERARY_LIST: 'getItineraryList',
    ADD_TO_EVENT: 'addToEvent',
    PIN_USER: 'getUserPin',
  };
  
  export const EVENT_TYPE = {
    SAVE_EVENT_LIST: 'saveEventList',
    SAVE_EVENT_LIST_LOAD_MORE: 'saveEventListLoadMore',
    SAVE_EVENT_DETAIL: 'saveEventDetail',
    SAVE_EVENT_ADD: 'saveEventAdd',
    SAVE_EVENT_DELETE: 'saveEventDelete',
    SAVE_EVENT_UPDATE: 'saveEventUpdate',
    SAVE_EVENT_PARTICIPATE: 'saveEventParticipate',
    EVENT_DETAIL_PARTICIPATE: 'saveParticipate',
    EVENT_LIST_ID: 'eventListId',
    EVENT_TASK_DELETE: 'eventTaskDelete',
    EVENT_TASK_DETAIL: 'saveeventTaskDetail',
    EVENT_TASK_COMPLETE: 'saveEventTaskComplete',
    CLEAR_EVENT: 'clearEvent',
    ADD_TO_CALENDER_EVENT: 'addToCalenderEvent',
    ADD_TO_CALENDER_TASK: 'addToCalenderTask',
    MONTHLY_SAVE_EVENT_LIST: 'saveMonthlyEventList',
    MONTHLY_SAVE_EVENT_LIST_LOAD_MORE: 'saveMonthlyEventListLoadMore',
    MONTHLY_SAVE_TASK_LIST: 'saveMonthlyTaskList',
    MONTHLY_SAVE_TASK_LIST_LOAD_MORE: 'saveMonthlyTaskListLoadMore',
    DELETE_MONTHLY_LIST : 'deleteMonthlyList',
    SAVE_SIDENOTE_LIST: 'saveSidenoteList',
    SAVE_SIDENOTE_LIST_LOAD_MORE: 'saveSidenoteListLoadMore',
    REMOVE_SIDENOTE: 'removeCard',
    MONTHLY_EVENT_UPDATE: 'updateMonthlyEvent',
    SAVE_CONNECTION_LIST: 'saveConnectionList',
    SAVE_CONNECTION_LIST_LOAD_MORE: 'saveConnectionListMore',
    REMOVE_CONNECTION: 'removeConnection',
    PINNED_USER_LIST: 'savePinnedUser',
    PINNED_USER_LIST_LOAD_MORE: 'savePinnedUserLoadMore',
  };
  
  export const GROUP_TYPE = {
    STATE_CLEAR: 'stateClear',
    SAVE_GROUP_ADD: 'saveGroupAdd',
    SAVE_GROUP_UPDATE: 'saveGroupUpdate',
    ADD_GROUP_MEMBER: 'addGroupMember',
    SAVE_GROUP_SUB_UPDATE: 'saveGroupSubUpdate',
    SAVE_SUB_GROUP_ADD: 'saveSubGroupAdd',
    SAVE_GROUP_DETAIL: 'saveGroupDetail',
    SAVE_SUB_GROUP_DETAIL: 'saveSubGroupDetail',
    CREATE_GROUP_MESSAGE: 'createGroupMessage',
    REPLY_GROUP_MESSAGE: 'replyGroupMessage',
    UPDATE_CREATE_GROUP_MESSAGE: 'updateCreateGroupMessage',
    UPDATE_REPLY_GROUP_MESSAGE: 'updateReplyGroupMessage',
    UPDATE_GROUP_PROFILE: 'getGroupProfileUpdate',
    MESSAGE_LIST: 'messageList',
    MESSAGE_LIST_LOAD_MORE: 'messageListLoadMore',
    MESSAGE_LIKE: 'messageLike',
    REAL_TIME_MESSAGE_LIKE: 'realTimeMessageLike',
    APPEND_MESSAGE: 'appendMessage',
    MESSAGE_DELETE: 'messageDelete',
    GROUP_LEAVE: 'groupLeave',
    GROUP_DELETE: 'getGroupDelete',
    GROUP_MEMBER_REMOVE: 'groupMemberRemove',
    SAVE_MEMBER_GROUP_LIST: 'saveMembersGroupList',
    SUB_GROUP_MEMBER_REMOVE: 'subGroupMemberRemove',
    GROUP_ARCHIVE_LIST: 'groupArchiveList',
    GROUP_ARCHIVE: 'getGroupArchive',
    GROUP_UNARCHIVE: 'getGroupUnarchive',
    CHAT_LIST: 'newChatList',
    CHAT_LIST_UPDATE: 'chatListUpdate',
    CHAT_DETAIL: 'getChatDetail',
    CHAT_READ: 'readChat',
    CHAT_MUTE: 'getChatMute',
    CHAT_PIN: 'getChatPin',
    CHAT_UNPIN: 'getChatUnpin',
    CHAT_BLOCK: 'getChatBlock',
    CHAT_CLEAR: 'getChatClear',
    CHAT_DELETE: 'getChatDelete',
    CHAT_ARCHIVE: 'getChatArchive',
    CHAT_ARCHIVE_LIST: 'getChatArchiveList',
    CHAT_UNARCHIVE: 'getChatUnarchive',
    BLOCK_USER_LIST: 'getBlockUserList',
    USER_BLOCK: 'getUserBlock',
    SAVE_EVENT_IN_CHAT: 'saveEventInChat',
    SAVE_POLL_IN_CHAT: 'savePollInChat',
    POLL_VOTE_IN_CHAT: 'savePollVoteInChat',
    POLL_DELETE_IN_CHAT: 'savePollDeleteInChat',
    POLL_UPDATE_IN_CHAT: 'savePollUpdateInChat',
    POLL_VOTE_FROM_SERVER: 'savePollVoteInChatFromServer',
    TASK_COMPLETE_IN_CHAT: 'saveTaskCompleteInChat',
    Current_Tab_Name: 'CurrentTabName',
    SUB_GROUP_PRIVATE: 'subGroupPrivate',
    SUB_GROUP_ID_DATA: 'subGroupIDData',
    ADD_MODERATOR: 'addGroupModerator',
    ADD_TO_CALENDER: 'addToCalender',
  };
  
  export const POLL_TYPE = {
    SAVE_POLL_LIST: 'savePollList',
    POLL_LIST_LOAD_MORE: 'pollListLoadMore',
    SAVE_POLL_ADD: 'savePollAdd',
    POLL_VOTE: 'savePollVote',
    SAVE_POLL_DETAIL: 'savePollDetail',
    SAVE_VOTER_LIST: 'saveVoterList',
    SAVE_POLL_DELETE: 'savePollDelete',
    SAVE_POLL_UPDATE: 'savePollUpdate',
    POLL_VOTE_SERVER: 'savePollVoteServer',
  };
  