// Api key list for call diffrent types of api response
export const API_DATA = {
  BASE_URL: 'https://api.prod.doyousidenote.com/api/v1/',
  // BASE_URL: 'http://192.168.0.235:8080/api/v1',

  LOGIN: 'login',
  SOCIAL_LOGIN: 'social',
  SIGNUP: 'signup',
  LOGOUT: 'logout',
  FORGOT_PASSWORD: 'forgot',
  CHANGE_PASSWORD: 'changepassword',
  VERIFICATION_MOBILENO: 'vcode/send',
  VERIFICATION_CODE: 'vcode/verify',
  SIGN_UP: 'signup',
  // LOGIN: 'login',
  PROFILE: 'me',
  UPDATEPROFILE: 'updateme',
  DASHBOARD: 'dashboard',
  TASKCOMPLETE: 'task/complete',
  TASKLIST: 'task/list',
  TASKDETAIL: 'task/detail',
  TASKADD: 'task/add',
  TASKDELETE: 'task/delete',
  TASKUPDATE: 'task/update',
  TASKLISTGROUPID: 'task/listByGroupId',
  USERALL: 'user/all',
  USER_TOKEN: 'user_token',
  CALENDAR_EVENT_TASK: 'user/filterEventTask',
  ADD_TO_CALENDAR: 'user/add-to-calendar',
  // CALENDAR_EVENT_TASK: 'user/filterEventTask',
  USER_CALENDAR_DAY: 'user/calendar',
  USER_CALENDAR_MONTH: 'user/monthly-calendar',
  MONTHLY_COUNT: 'user/monthly-calendar-count',
  MONTH_TASK_LIST: 'task/monthly-calendar-data',
  PIN_USER: 'user/add-pin',
  PINNED_USER_LIST: 'user/pinned-list',
  CATEGORY_EVENTLIST: 'group/calendar/events',
  GROUPLIST: 'group/list',
  GROUPADD: 'group/add',
  GROUPUPDATE: 'group/update',
  GROUPSUBUPDATE: 'group/subgroup/update',
  SUBGROUPADD: 'group/subgroup/add',
  GROUPDETAIL: 'group/detail',
  GROUPMEMBERREMOVE: 'group/member/remove',
  GROUPLEAVE: 'group/leave',
  EVENTLISTID: 'event/listByGroupId',
  GROUPMEMBERADD: 'group/member/add',
  GROUPARCHIVELIST: 'group/archiveList',
  GROUPARCHIVE: 'group/archive',
  GROUPUNARCHIVE: 'group/unarchive',
  GROUPDELETE: 'group/delete',
  GROUPMODERATOR: 'group/moderatorAddRemove',

  MYCONNECTIONS: 'myconnections',
  CONNECTIONDETAILS: 'checkconnection',

  EVENTLIST: 'event/list',
  EVENTDETAIL: 'event/detail',
  EVENTADD: 'event/add',
  EVENTDELETE: 'event/delete',
  EVENTUPDATE: 'event/update',
  EVENTTASKDETAIL: 'event/task/detail',
  EVENTPARTICIPATE: 'event/participate',
  EVENTTASKDELETE: 'event/task/delete',
  EVENTTASKCOMPLETE: 'event/task/complete',
  MONTH_EVENT_LIST: 'event/monthly-calendar-data',

  INVITEFRIEND: 'invitation/send',
  ACCEPTFRIEND: 'invitation/accept',
  JOINFRIEND: 'invitation/join',
  VALIDATEURL: 'invitation/validate',
  GROUP_INVITATION_JOIN: 'group-member/invitation/response',

  CHATLIST: 'chat/list',
  CHATDETAIL: 'chat/detail',
  CHATREAD: 'chat/read',
  CHATMUTE: 'chat/mute',
  CHATBLOCK: 'chat/block',
  GROUPMSGSEND: 'chat/groupmessage/send',
  MESSAGELIST: 'chat/message/list',
  MSGLIKE: 'chat/message/like',
  CHATMESSAGEREPORT: 'chat/message/report',
  MESSAGEDELETE: 'chat/message/delete',
  CHATCLEAR: 'chat/clear',
  CHATDELETE: 'chat/delete',
  ONETOONEMSGSEND: 'chat/message/send',
  CHATPIN: 'chat/pin',
  CHATUNPIN: 'chat/unpin',
  CHATARCHIVE: 'chat/archive',
  CHATARCHIVELIST: 'chat/archiveList',
  CHATUNARCHIVE: 'chat/unarchive',
  BLOCKUSERLIST: 'chat/blockList',
  GROUPPROFILEUPDATE: 'group/updatePhoto',
  USERTYPING: 'chat/message/typing',
  BLOCKUSER: 'user/block',
  BLOCKLIST: 'user/blockList',
  SEND_REQUEST: 'invitation-for-app',
  SEND_CONTACT: 'contact-invitation-list',

  NOTIFICATION_LIST: 'notification/list',
  NOTIFICATION_READ: 'notification/read',
  NOTIFICATION_CLEAR_ALL: 'notification/clearAll',

  POLLLIST: 'poll/list',
  POLLADD: 'poll/add',
  POLLVOTE: 'poll/vote',
  POLLDETAILS: 'poll/detail',
  POLLVOTERS: 'poll/voterList',
  POLLDELETE: 'poll/delete',
  POLLUPDATE: 'poll/update',

  UPDATE_SETTINGS: 'updateSettings',
  LIKE_USER_LIST: 'chat/message/likedUsers',

  DELETE_ACCOUNT: 'removeAccount',
  ADD_ITINERARY: 'itinerary/add',
  ITINERARY_DETAILS: 'itinerary/detail',
  PUBLISH_ITINERARY: 'itinerary/publish',
  UPDATE_ITINERARY: 'itinerary/update',
  GET_DRAFT_ITINERARY: 'itinerary/draft-list',
  GET_ITINERARY: 'itinerary/published-list',
  GROUP_INVITATION_LIST: 'group-invitation/list',
  CONNECTIONS_LIST: 'invitation/list',
  DISCONNECT: 'disconnect',
};
