import {Platform} from 'react-native';

export const IMAGES = {
  splash: require('../assets/images/image/splashscreen.imageset/splashscreen.png'),
  backArrow: require('../assets/images/image/backarrow.imageset/backarrow.png'),
  // loading: {
  //   uri:
  //     Platform.OS === 'ios'
  //       ? require('../assets/images/image/loading.imageset/loading.gif')
  //       : require('../assets/images/image/loading.imageset/loading.png'),
  // },
  // loading: require('../assets/images/image/loading.imageset/loading.gif'), // Adjust for iOS as needed
  // typing: require('../assets/images/image/typing.imageset/typing.gif'),
  phone: require('../assets/images/image/phone.imageset/phone.png'),
  visible: require('../assets/images/image/visible.imageset/visible.png'),
  invisible: require('../assets/images/image/invisible.imageset/invisible.png'),
  mail: require('../assets/images/image/mail.imageset/mail.png'),
  avtar: require('../assets/images/image/avtar.imageset/avtar.png'),
  addIcon: require('../assets/images/image/add_icon.imageset/add_icon.png'),
  clearIcon: require('../assets/images/image/clear_icon.imageset/clear_icon.png'),
  // image1: require('../assets/images/image/image1.imageset/image1.png'),
  image: require('../assets/images/image/newsidelogo.imageset/newsidelogo.png'),
  more: require('../assets/images/image/more_icon.imageset/more_icon.png'),
  noChatImage: require('../assets/images/image/open_doodles_unboxing.imageset/open_doodles_unboxing.png'),
  // sortIcon: require('../assets/images/image/drawable/sort_icon.png'),
  groupIcon: require('../assets/images/image/users_icon.imageset/users_icon.png'),
  HOME_TAB: require('../assets/images/image/home_tab.imageset/home_tab.png'),
  CHATS_TAB: require('../assets/images/image/chats_tab.imageset/chats_tab.png'),
  EVENTS_TAB: require('../assets/images/image/events_tab.imageset/events_tab.png'),
  HOME_TAB_ACTIVE: require('../assets/images/image/home_tab_active.imageset/home_tab_active.png'),
  CHATS_TAB_ACTIVE: require('../assets/images/image/chats_tab_active.imageset/chats_tab_active.png'),
  EVENTS_TAB_ACTIVE: require('../assets/images/image/events_tab_active.imageset/events_tab_active.png'),
  open_doodles_laying_down: require('../assets/images/image/open_doodles_laying_down.imageset/open_doodles_laying_down.png'),
  open_doodles_zombieing: require('../assets/images/image/open_doodles_zombieing.imageset/open_doodles_zombieing.png'),
  open_doodles_zombieing2: require('../assets/images/image/open_doodles_zombieing2.imageset/open_doodles_zombieing2.png'),
  open_doodles_unboxing: require('../assets/images/image/open_doodles_unboxing.imageset/open_doodles_unboxing.png'),
  fab: require('../assets/images/image/fab.imageset/fab.png'),
  FAB_CHAT: require('../assets/images/image/fabchat.imageset/fabchat.png'),
  FAB_EVENTS: require('../assets/images/image/fabevents.imageset/fabevents.png'),
  FAB_TASKS: require('../assets/images/image/fabtasks.imageset/fabtasks.png'),
  imageShape: require('../assets/images/image/image_shape.imageset/image_shape.png'),
  sidenote_logo: require('../assets/images/image/newsidenotelogo.imageset/newsidenotelogo.png'),
  userIcon: require('../assets/images/image/users_group.imageset/users_group.png'),
  openDoodlesLoving: require('../assets/images/image/open_doodles_loving.imageset/open_doodles_loving.png'),
  search: require('../assets/images/image/search.imageset/search.png'),
  InviteIcon: require('../assets/images/image/invite_icon.imageset/invite_icon.png'),
  rightArrow: require('../assets/images/image/right_arrow.imageset/right_arrow.png'),
  shareIcon: require('../assets/images/image/share_icon.imageset/share_icon.png'),
  uncheck: require('../assets/images/image/uncheck.imageset/uncheck.png'),
  check: require('../assets/images/image/check.imageset/check.png'),
  check2: require('../assets/images/image/check_icon3.imageset/check_icon3.png'),
  edit: require('../assets/images/image/edit.imageset/edit.png'),
  sliderImageOne: require('../assets/images/image/slider_image_one.imageset/slider_image_one.png'),
  sliderImageTwo: require('../assets/images/image/slider_image_two.imageset/slider_image_two.png'),
  sliderImageThree: require('../assets/images/image/slider_image_three.imageset/slider_image_three.png'),
  onboardingScreen: require('../assets/images/image/onboarding_screen.imageset/onboarding_screen.png'),
  bgHeader: require('../assets/images/image/bg_header.imageset/bg_header.png'),
  rectangleBtn: require('../assets/images/image/rectangle_btn.imageset/rectangle_btn.png'),
  contacts: require('../assets/images/image/contacts.imageset/contacts.png'),
  settings: require('../assets/images/image/settings.imageset/settings.png'),
  notes: require('../assets/images/image/notes.imageset/notes.png'),
  lock: require('../assets/images/image/lock.imageset/lock.png'),
  help: require('../assets/images/image/help.imageset/help.png'),
  // bell: require('../assets/images/image/bell.imageset/bell.png'),
  uncheckIcon: require('../assets/images/image/uncheck_icon.imageset/uncheck_icon.png'),
  checkIcon: require('../assets/images/image/check_icon.imageset/check_icon.png'),
  uncheckIcon2: require('../assets/images/image/uncheck_icon2.imageset/uncheck_icon2.png'),
  checkIcon2: require('../assets/images/image/check_icon2.imageset/check_icon2.png'),
  addTask: require('../assets/images/image/add_task.imageset/add_task.png'),
  addPoll: require('../assets/images/image/polls_icon.imageset/polls_icon.png'),
  calendarIcon: require('../assets/images/image/calendar_icon.imageset/calendar_icon.png'),
  calendar_icon2: require('../assets/images/image/calendar_icon2.imageset/calendar_icon2.png'),
  dashIcon: require('../assets/images/image/dash_icon.imageset/dash_icon.png'),
  clockIcon: require('../assets/images/image/clock_icon.imageset/clock_icon.png'),
  usersGroup: require('../assets/images/image/users_group.imageset/users_group.png'),
  subtask: require('../assets/images/image/subtask.imageset/subtask.png'),
  plusIcon: require('../assets/images/image/plus_icon.imageset/plus_icon.png'),
  plusThin: require('../assets/images/image/plus_thin.imageset/plus_thin.png'),
  closeIconBorder: require('../assets/images/image/close_icon_border.imageset/close_icon_border.png'),
  downArrow: require('../assets/images/image/down_arrow.imageset/down_arrow.png'),
  upArrow: require('../assets/images/image/up_arrow.imageset/up_arrow.png'),
  checkMark: require('../assets/images/image/check_mark.imageset/check_mark.png'),
  deleteIcon: require('../assets/images/image/delete_icon.imageset/delete_icon.png'),
  // leftReply: require('../assets/images/image/left_reply.imageset/left_reply.png'),
  // rightReply: require('../assets/images/image/right_reply.imageset/right_reply.png'),
  prevArrow: require('../assets/images/image/prev_arrow.imageset/prev_arrow.png'),
  nextArrow: require('../assets/images/image/next_arrow.imageset/next_arrow.png'),
  addEvent: require('../assets/images/image/add_event.imageset/add_event.png'),
  eventImage: require('../assets/images/image/event_image.imageset/event_image.png'),
  star: require('../assets/images/image/star.imageset/star.png'),
  photo: require('../assets/images/image/photo.imageset/photo.png'),
  mapPin: require('../assets/images/image/map_pin.imageset/map_pin.png'),
  bellIcon: require('../assets/images/image/bell_icon.imageset/bell_icon.png'),
  closeIcon: require('../assets/images/image/close_icon.imageset/close_icon.png'),
  x_icon: require('../assets/images/image/x_icon.imageset/x_icon.png'),
  // bars_gray: require('../assets/images/image/bars_gray.imageset/bars_gray.png'),
  pinIcon: require('../assets/images/image/pin.imageset/pin.png'),
  deleteNewIcon: require('../assets/images/image/trash.imageset/trash.png'),
  CIRCLE_GROUP: require('../assets/images/image/image_shape.imageset/image_shape.png'),
  MSG_IMG: require('../assets/images/image/msg_dummy.imageset/msg_dummy.png'),
  PVT_CHAT: require('../assets/images/image/private_chat.imageset/private_chat.png'),
  mini: require('../assets/images/image/mini.imageset/mini.png'),
  // muute: require('../assets/images/image/mute.imageset/mute.png'),
  replay_line: require('../assets/images/image/replay_line.imageset/replay_line.png'),
  sort_icon: require('../assets/images/image/app_icon_gray.imageset/app_icon_gray.png'),
  gradient_layer: require('../assets/images/image/gradient_layer.imageset/gradient_layer.png'),
  block: require('../assets/images/image/block_user.imageset/block_user.png'),
  notification: require('../assets/images/image/notification.imageset/notification.png'),
  PromtNotification: require('../assets/images/image/undraw_my_notification/notification.png'),
  private_Icon: require('../assets/images/image/private_lock.imageset/private_lock.png'),
  like: require('../assets/images/image/heart.imageset/heart.png'),
  theme_Icon: require('../assets/images/image/night_mode.imageset/night_mode.png'),
  chat_like: require('../assets/images/image/like.imageset/like.png'),
  copy: require('../assets/images/image/copy.imageset/copy.png'),
  replyLeft: require('../assets/images/image/reply_left.imageset/reply_left.png'),
  replyRight: require('../assets/images/image/reply_right.imageset/reply_right.png'),
  report: require('../assets/images/image/report.imageset/report.png'),
  shortAppLogo: require('../assets/images/image/short_app_logo.imageset/short_app_logo.png'),
  // newArrow: require('../assets/images/image/new_arrow.imageset/new_arrow.png'),
  directInbox: require('../assets/images/image/direct_inbox.imageset/direct_inbox.png'),
  iconAddCircle: require('../assets/images/image/icon_addcircle.imageset/icon_addcircle.png'),
  calAddIcon: require('../assets/images/image/calendar_float.imageset/calendar_float.png'),
  undrawMyNotifications: require('../assets/images/image/undraw_my_notifications.imageset/undraw_my_notifications.png'),
  add_moderator: require('../assets/images/image/add_moderator.imageset/add_moderator.png'),
  add_task_event: require('../assets/images/image/add_task_event.imageset/add_task_event.png'),
  event_icon: require('../assets/images/image/event_icon.imageset/event_icon.png'),
  icon_calendar_add: require('../assets/images/image/icon_calendar_add.imageset/icon_calendar_add.png'),
  icon_circle_check: require('../assets/images/image/icon_circle_check.imageset/icon_circle_check.png'),
  notification_list_img: require('../assets/images/image/notification_list_img.imageset/notification_list_img.png'),
  notification_profile_dp: require('../assets/images/image/notification_profile_dp.imageset/notification_profile_dp.png'),
  chat_name_icon: require('../assets/images/image/chat_name_icon.imageset/chat_name_icon.png'),
  new_sidenote: require('../assets/images/image/new_sidenote.imageset/new_sidenote.png'),
  new_sidenote2: require('../assets/images/image/new_sidenote2.imageset/new_sidenote2.png'),
  new_task: require('../assets/images/image/new_task.imageset/new_task.png'),
  task_icon2: require('../assets/images/image/task_icon2.imageset/task_icon2.png'),
  connection: require('../assets/images/image/connection.imageset/connection.png'),
  direct_message: require('../assets/images/image/direct_message.imageset/direct_message.png'),
  link_icon: require('../assets/images/image/link_icon.imageset/link_icon.png'),
  link_circle_icon: require('../assets/images/image/link_circle_icon.imageset/link_circle_icon.png'),
  calendar_pen_icon: require('../assets/images/image/calendar_pen_icon.imageset/calendar_pen_icon.png'),
  notes_icon: require('../assets/images/image/notes_icon.imageset/notes_icon.png'),
  direct_msg_icon: require('../assets/images/image/direct_msg_icon.imageset/direct_msg_icon.png'),
  globe_color_icon: require('../assets/images/image/globe_color_icon.imageset/globe_color_icon.png'),
  categories_icon: require('../assets/images/image/categories_icon.imageset/categories_icon.png'),
  upload_img_placeholder: require('../assets/images/image/upload_img_placeholder.imageset/upload_img_placeholder.jpg'),
  chat_icon: require('../assets/images/image/chat_icon.imageset/chat_icon.png'),
  add_task_icon: require('../assets/images/image/add_task_icon.imageset/add_task_icon.png'),
  send_icon: require('../assets/images/image/send_icon.imageset/send_icon.png'),
  disconnect_icon: require('../assets/images/image/disconnect_icon.imageset/disconnect_icon.png'),
  calendar_no_data: require('../assets/images/image/calendar_no_data.imageset/calendar_no_data.png'),
  insert_link_icon: require('../assets/images/image/insert_link_icon.imageset/insert_link_icon.png'),
};
