import { StyleSheet, StatusBar, Platform } from 'react-native';

import { COMMON_STYLE, STYLES } from '@themes';
import { Responsive } from '@helpers';

export const style = theme =>
  StyleSheet.create({
    ...COMMON_STYLE,
    ...STYLES,
    screenBG: {
      flex: 1,
    },
    header: {
      // height: Platform.OS === 'ios' ? 90 : 80,
      paddingHorizontal: 15,
      // borderBottomWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      flexDirection: 'row',
      alignItems: 'flex-end',
      // paddingTop: StatusBar.currentHeight + Responsive.getWidth(13),
      paddingBottom: Responsive.getWidth(3),
    },
    headerLeft: {
      width: 30,
    },
    headerCenter: {
      flex: 1,
      // flexDirection: 'row',
      // alignItems: 'center',
      // justifyContent: 'center',
      paddingBottom: 5,
    },
    headerCenterTitle: {
      ...STYLES.textStyle(14, theme?.colors?.WHITE, 'BASE'),
    },
    headerRight: {
      width: 50,
      alignItems: 'flex-end',
      // marginLeft: -20,
      // flexDirection: 'row',
    },
    eventScroll: {
      paddingHorizontal: Responsive.getWidth(6),
    },
    headerLeftIcon: {
      ...STYLES.textStyle(20, theme?.colors?.RED_500),
      marginLeft: -5,
    },
    headerRightImgWrap: {
      width: Responsive.getWidth(9),
      height: Responsive.getWidth(9),
      borderRadius: 75,
      overflow: 'hidden',
    },
    headerRightImg: {
      width: '100%',
      height: '100%',
    },
    safeAreaStyle: {
      width: '100%',
      height: '100%',
      backgroundColor: theme?.colors?.DARK_OPACITY,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      position: 'absolute',
    },
    alertBoxStyle: {
      width: Responsive.getWidth(100),
      maxHeight: Responsive.getHeight(55),
      borderRadius: Responsive.getWidth(3),
      backgroundColor: theme?.colors?.WHITE,
    },
    closeButtonStyle: {
      width: Responsive.getWidth(8),
      height: Responsive.getWidth(8),
      alignSelf: 'flex-end',
      margin: Responsive.getWidth(2),
      backgroundColor: theme?.colors?.TRANSPARENT,
    },
    button: {
      paddingHorizontal: 20,
      borderRadius: 30,
      backgroundColor: theme?.colors?.RED_500,
    },
    closeIconStyle: {
      width: Responsive.getWidth(4),
      height: Responsive.getWidth(4),
    },
    profileBtnViewStyle: {
      marginVertical: Responsive.getHeight(2),
      alignItems: 'center',
      justifyContent: 'space-evenly',
      height: 150,
    },
    chatIconBtn: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    chatIcon: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_300),
    },
    chatFooter: {
      paddingHorizontal: 15,
      borderTopWidth: 1,
      borderColor: theme?.colors?.GRAY_800,
      backgroundColor: theme?.colors?.TRANSPARENT,
      paddingBottom: Platform.OS === 'ios' ? Responsive.getWidth(3) : 0,
    },
    inputContainer: {},
    msgInput: {
      ...STYLES.textStyle(14, theme?.colors?.WHITE, 'BASE'),
      minHeight: 50,
      maxHeight: 100,
      paddingTop: 10,
    },
    footerIconRow: {
      height: 50,
      flexDirection: 'row',
      alignItems: 'center',
    },
    footerIconColLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    footerIconColRight: {
      width: 100,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
    },
    footerIconBtn: {
      flex: 1,
    },
    footerIcon: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_100),
    },
    footerLeftIconBtn: {},
    footerLeftIcon: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_100),
    },
    noMsgContainer: {
      flex: 1,
      padding: 15,
      marginHorizontal: Responsive.getWidth(5),
    },
    alertTitleStyle: {
      ...COMMON_STYLE.textStyle(16, theme?.colors?.BLACK, 'BOLD', 'center'),
    },
    descriptionStyle: {
      ...COMMON_STYLE.textStyle(14, theme?.colors?.DARK_GRAY, undefined, 'center'),
      marginHorizontal: Responsive.getWidth(2),
      marginVertical: Responsive.getHeight(1),
    },
    profileBtnViewStyle: {
      marginVertical: Responsive.getHeight(2),
      alignItems: 'center',
      justifyContent: 'space-evenly',
      height: 150,
    },
    noMsgTxt: {
      ...STYLES.textStyle(14, theme?.colors?.GRAY_300, 'BASE', 'center'),
      lineHeight: 24,
      width: Responsive.getWidth(80),
      alignSelf: 'center',
    },

    msgContainer: {
      paddingHorizontal: 10,
      flex: 1,
      // // flexDirection: 'column-reverse',
    },
    msgContainerLeft: {
      width: Responsive.getWidth(85),
      marginBottom: Responsive.getWidth(5),
    },
    msgContainerRight: {
      width: Responsive.getWidth(70),
      marginBottom: Responsive.getWidth(5),
      marginLeft: 'auto',
      marginRight: 0,
    },
    msgRow: {
      flexDirection: 'row',
      alignItems: 'flex-end',
    },
    senderImgWrap: {
      width: Responsive.getWidth(8),
      height: Responsive.getWidth(8),
      borderRadius: 75,
      overflow: 'hidden',
      // marginBottom: 23,
    },
    userImg: {
      width: '100%',
      height: '100%',
    },
    closeIconStyle: {
      width: Responsive.getWidth(4),
      height: Responsive.getWidth(4),
    },
    msgTxtBox: {
      flex: 1,
      width: Responsive.getWidth(60),
      marginHorizontal: Responsive.getWidth(3),
    },
    msgTimeTxt: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_200, 'BASE', 'left'),
      marginBottom: 5,
    },
    msgTimeTxtRight: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_200, 'BASE', 'right'),
      marginBottom: 5,
    },
    typeMsgTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      fontSize: 14,
      lineHeight: 20,
      borderWidth: 1,
      borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      padding: 10,
    },
    typeMsgTxtImgReply: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      fontSize: 14,
      lineHeight: 20,
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      paddingBottom: 10,
    },
    typeMsgTxtInnerView: {
      // borderWidth: 1,
      // borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      backgroundColor: 'rgba(255,255,255,0.2)',
      padding: 10,
    },
    typeMsgTxtInnerLeftView: {
      backgroundColor: theme?.colors?.RED_500,
      // borderWidth: 1,
      // borderColor: theme?.colors?.RED_500,
      borderRadius: 10,
      padding: 10,
    },
    typeMsgInnerTxt1: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_200, 'BASE', 'left'),
      backgroundColor: 'rgba(207, 186, 163, 0.1)',
      fontSize: 14,
      lineHeight: 20,
      borderRadius: 8,
      padding: 10,
      marginBottom: 5,
      overflow: 'hidden',
    },
    typeMsgInnerTxt1Left: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      backgroundColor: 'rgba(207, 186, 163, 0.3)',
      fontSize: 14,
      lineHeight: 20,
      borderRadius: 8,
      padding: 10,
      marginBottom: 5,
      overflow: 'hidden',
    },
    typeMsgInnerTxt2: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      fontSize: 14,
      lineHeight: 20,
    },
    typeMsgInnerTxt2Left: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'left'),
      fontSize: 14,
      lineHeight: 20,
    },
    shareImgView: {
      flex: 1,
      height: Responsive.getHeight(18),
      borderRadius: 10,
      overflow: 'hidden',
    },
    shareImg: {
      width: '100%',
      height: '100%',
    },
    replyBtnRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    replyBtnTxt: {
      ...STYLES.textStyle(10, theme?.colors?.PURPLE_500, 'BASE', 'left'),
      marginTop: 5,
      marginRight: 15,
    },
    msgLikeViewLeft: {
      position: 'absolute',
      right: Responsive.getHeight(1),
      bottom: -Responsive.getHeight(2),
      backgroundColor: '#28283E',
      borderWidth: 2,
      borderColor: '#03021D',
      borderRadius: 30,
      paddingVertical: Responsive.getWidth(0.3),
      paddingHorizontal: Responsive.getWidth(3),
      zIndex: 1051,
    },
    msgLikeViewRight: {
      position: 'absolute',
      left: Responsive.getHeight(1),
      bottom: -Responsive.getHeight(2),
      backgroundColor: '#28283E',
      borderWidth: 2,
      borderColor: '#03021D',
      borderRadius: 30,
      paddingVertical: Responsive.getWidth(0.3),
      paddingHorizontal: Responsive.getWidth(3),
      zIndex: 1051,
    },
    msgLikeBtn: {
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      width: Responsive.getHeight(2),
      height: Responsive.getHeight(2),
      // backgroundColor: 'yellow',
      zIndex: 1,
    },
    // msgLikeBtn: {
    //   flexDirection: 'row',
    //   alignItems: 'center',
    //   borderWidth: 1,
    //   borderColor: theme?.colors?.GRAY_800,
    //   borderRadius: 10,
    //   // paddingHorizontal: 8,
    //   justifyContent: 'center',
    //   paddingVertical: 2,
    //   // marginBottom: 20,
    //   minWidth: 40,
    //   marginBottom: 5,
    // },
    msgLikeBtn1: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 10,
      justifyContent: 'flex-end',
      paddingVertical: 2,
      minWidth: 40,
      marginBottom: 5,
    },
    msgLikeBtn2: {
      flexDirection: 'row',
      alignItems: 'center',
      borderRadius: 10,
      justifyContent: 'flex-start',
      paddingVertical: 2,
      minWidth: 40,
      marginBottom: 5,
    },
    likeIcon: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_300),
      position: 'absolute',
      zIndex: 5,
      marginLeft: -Responsive.getWidth(1),
    },
    likeIcon2: {
      ...STYLES.textStyle(12, 'red'),
      position: 'absolute',
      zIndex: 5,
      marginLeft: -Responsive.getWidth(1),
      shadowColor: '#000',
      shadowOffset: {
        width: -1,
        height: -1,
      },
      shadowOpacity: 1,
      shadowRadius: 1,
      elevation: 10,
    },
    likeCountTxt: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_50),
      position: 'absolute',
      zIndex: 6,
      marginLeft: Responsive.getWidth(2),
    },
    replyLeftView: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 15,
      width: Responsive.getWidth(82),
      marginLeft: 'auto',
    },
    replyImgWrap: {
      width: Responsive.getWidth(7),
      height: Responsive.getWidth(7),
      borderRadius: 75,
    },
    replyViewContent: {
      paddingLeft: Responsive.getWidth(2),
    },
    replyNameTxt: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_300),
    },
    replyNameInnerTxt: {
      ...STYLES.textStyle(11, theme?.colors?.WHITE),
    },
    replyTxt2: {
      ...STYLES.textStyle(10, theme?.colors?.GRAY_100),
      marginTop: 3,
    },
    eventView: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      backgroundColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      padding: 10,
    },
    eventDateView: {
      width: Responsive.getWidth(15),
      height: Responsive.getWidth(15),
      borderRadius: 10,
      backgroundColor: theme?.colors?.GRAY_800,
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventDetail: {
      flex: 1,
      paddingLeft: 10,
    },
    eventDateTxt1: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
      textTransform: 'uppercase',
    },
    eventDateTxt2: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_300, 'BOLD'),
      marginTop: 3,
    },
    eventTitle: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
    },
    eventSubjectTxt: {
      ...STYLES.textStyle(11, theme?.colors?.GRAY_200, 'BASE'),
      marginTop: 3,
    },
    eventDate: {
      ...STYLES.textStyle(11, theme?.colors?.GRAY_200, 'BASE'),
      marginTop: 3,
    },
    optionView: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      padding: 10,
    },
    optionQuestionTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
    },
    optionRow: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(9),
      borderRadius: 8,
      backgroundColor: theme?.colors?.GRAY_800,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      marginTop: 8,
      overflow: 'hidden',
    },
    optionRowTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
      zIndex: 1,
    },
    optionRowTxtIcon: {
      ...STYLES.textStyle(14, theme?.colors?.GRAY_50),
    },
    optionProgress: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '0%',
      height: '100%',
      backgroundColor: theme?.colors?.RED_500,
    },

    tabHeader: {
      flexDirection: 'row',
      borderBottomWidth: 0,
      borderColor: 'rgba(0,0,0,0.08)',
      width: '100%',
    },
    tabStyle: {
      flex: 1,
      paddingHorizontal: Responsive.getWidth(10),
      paddingVertical: Responsive.getWidth(15),
      color: theme?.colors?.WHITE,
    },
    selectTabStyle: {
      borderBottomWidth: 3,
      borderColor: '#E94742',
    },
    tabTextStyle: {
      textAlign: 'center',
      color: '#020108',
      fontSize: Responsive.getWidth(18),
    },
    selectTabTextStyle: {
      color: '#222B45',
    },
    titleStyle: {
      textTransform: 'none',
      ...STYLES.textStyle(14, theme?.colors?.GRAY_300, 'BOLD', 'center'),
    },
    titleActiveStyle: {
      textTransform: 'none',
      ...STYLES.textStyle(14, theme?.colors?.RED_500, 'BOLD', 'center'),
    },
    sidenotHiddenRow: {
      height: '84%',
      flexDirection: 'row',
      justifyContent: 'flex-end',
      backgroundColor: theme?.colors?.BLACK_100,
      borderRadius: 12,
      overflow: 'hidden',
      paddingRight: 20,
    },
    sidenotHiddenCol: {
      width: 100,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sidenotHiddenColIcon: {
      ...STYLES.textStyle(18, theme?.colors?.WHITE),
    },
    eventItem: {
      borderRadius: Responsive.getWidth(6),
      overflow: 'hidden',
      backgroundColor: theme?.colors?.GRAY_900,
      borderWidth: 1,
      borderColor: 'rgba(207, 186, 163, 0.24)',
      marginTop: 8,
      minHeight: Responsive.getWidth(40),
    },
    eventImage: {
      width: '100%',
      height: Responsive.getWidth(54),
    },
    eventContent: {
      position: 'absolute',
      bottom: 0,
      padding: Responsive.getWidth(6),
      width: '100%',
      height: '100%',
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    eventContentRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    eventItem: {
      borderRadius: Responsive.getWidth(6),
      overflow: 'hidden',
      backgroundColor: theme?.colors?.GRAY_900,
      borderWidth: 1,
      borderColor: 'rgba(207, 186, 163, 0.24)',
      marginTop: 8,
      minHeight: Responsive.getWidth(40),
    },
    eventImage: {
      width: '100%',
      height: Responsive.getWidth(54),
    },
    eventContent: {
      position: 'absolute',
      bottom: 0,
      padding: Responsive.getWidth(6),
      width: '100%',
      height: '100%',
      flexDirection: 'column',
      justifyContent: 'space-between',
    },
    eventContentRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    smallBtn: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      height: Responsive.getWidth(9),
      paddingHorizontal: Responsive.getWidth(3),
      borderRadius: Responsive.getWidth(9),
      justifyContent: 'center',
      alignItems: 'center',
      width: 'auto',
      alignSelf: 'flex-end',
    },
    smallBtnText: {
      ...STYLES.textStyle(12, theme?.colors?.WHITE, 'BASE', 'center'),
    },
    eventTitle: {
      ...STYLES.textStyle(20, theme?.colors?.WHITE, 'BASE', 'left'),
      marginBottom: 2,
      textShadowColor: 'rgba(0, 0, 0, 0.50)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 10,
    },
    eventText: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE', 'left'),
      opacity: 0.8,
      textShadowColor: 'rgba(0, 0, 0, 0.50)',
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 10,
    },
    modalContainer: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.7)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: Responsive.getWidth(6),
    },
    modalView: {
      width: '100%',
      backgroundColor: 'rgba(24, 24, 24, 0.7)',
      padding: Responsive.getWidth(5),
      borderRadius: Responsive.getWidth(4),
    },
    modalImageView: {
      width: Responsive.getWidth(35),
      height: Responsive.getWidth(35),
      backgroundColor: '#ECECEC',
      alignSelf: 'center',
      marginBottom: 35,
    },
    modalTitle: {
      ...COMMON_STYLE.textStyle(16, theme?.colors?.DARK_GRAY, 'BOLD', 'center'),
      marginBottom: 6,
    },
    modalText: {
      ...COMMON_STYLE.textStyle(13, theme?.colors?.WHITE, 'BASE', 'center'),
      marginBottom: 15,
      marginTop: 10,
    },
    modalButtonText: {
      ...COMMON_STYLE.textStyle(16, theme?.colors?.BLACK, 'BOLD', 'center'),
      marginTop: 20,
    },
    cellSeprator: {
      borderWidth: 0.3,
      borderColor: theme?.colors?.INPUT_GRAY_COLOR,
    },
    ListItemAccordion: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    checkboxItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: Responsive.getWidth(5),
    },
    checkboxBody: {
      flex: 1,
      paddingHorizontal: Responsive.getWidth(8),
    },
    checkboxTextStyle: {
      color: theme?.colors?.WHITE,
      fontSize: Responsive.getWidth(16),
    },
    sectionHeaderTitle: {
      ...STYLES.textStyle(15, theme?.colors?.RED_500, 'BOLD', 'left'),
      marginTop: Responsive.getWidth(2),
    },
    dmMsgRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      paddingVertical: Responsive.getWidth(3),
    },
    dmMsgTxt: {
      flex: 1,
      ...STYLES.textStyle(12, theme?.colors?.GRAY_200, 'BASE', 'left'),
      backgroundColor: 'rgba(207, 186, 163, 0.1)',
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 8,
    },
    dmMsgIcon: {
      marginLeft: 15,
      ...STYLES.textStyle(11, theme?.colors?.GRAY_100),
      backgroundColor: theme?.colors?.GRAY_300,
      width: 20,
      height: 20,
      lineHeight: 20,
      textAlign: 'center',
      borderRadius: 75,
      overflow: 'hidden',
    },
    shareImgView2: {
      flex: 1,
      height: Responsive.getHeight(14),
      borderRadius: 10,
      overflow: 'hidden',
      marginBottom: 5,
    },
    pollCard: {
      position: 'relative',
      paddingHorizontal: Responsive.getWidth(3),
      paddingVertical: Responsive.getWidth(2),
      backgroundColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      width: '100%',
    },
    polluserRow: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderColor: 'rgba(99, 94, 92, 0.24)',
      paddingBottom: Responsive.getWidth(2),
      marginBottom: Responsive.getWidth(2),
    },
    polluserImg: {
      width: Responsive.getWidth(7),
      height: Responsive.getWidth(7),
      borderRadius: 75,
      backgroundColor: theme?.colors?.GRAY_100,
    },
    polluserTxt: {
      flex: 1,
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      paddingLeft: Responsive.getWidth(4),
    },
    polluserTxtInner: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BOLD', 'left'),
    },
    pollCardTitle: {
      ...STYLES.textStyle(14, theme?.colors?.GRAY_100, 'BASE', 'left'),
      marginBottom: Responsive.getWidth(3),
    },
    chatPollCardTitle: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      marginBottom: Responsive.getWidth(3),
    },
    pollProgress: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(10),
      borderRadius: 75,
      backgroundColor: 'rgba(207, 186, 163, 0.1)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 8,
      paddingHorizontal: Responsive.getWidth(3),
      overflow: 'hidden',
      marginBottom: 10,
    },
    pollProgressTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_100, 'BASE', 'left'),
      zIndex: 1204,
    },
    pollProgressView: {
      position: 'absolute',
      // width: '100%',
      height: '100%',
      borderRadius: 8,
      backgroundColor: theme?.colors?.RED_500,
    },
    pollVoteRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 3,
    },
    pollVoteTxt: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_300, 'BASE', 'left'),
    },
    pollTextProgress: {
      position: 'relative',
      width: '100%',
      height: Responsive.getWidth(10),
      borderRadius: 75,
      backgroundColor: 'rgba(207, 186, 163, 0.1)',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 8,
      paddingHorizontal: Responsive.getWidth(3),
      overflow: 'hidden',
      marginBottom: 10,
    },
    pollTextProgressActive: {
      position: 'relative',
      width: '100',
      height: Responsive.getWidth(10),
      borderRadius: 75,
      backgroundColor: theme?.colors?.RED_500,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 8,
      paddingHorizontal: Responsive.getWidth(3),
      overflow: 'hidden',
      marginBottom: 10,
    },
    eventView: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: theme?.colors?.GRAY_800,
      borderRadius: 10,
      padding: 10,
    },
    eventDateView: {
      width: Responsive.getWidth(15),
      height: Responsive.getWidth(15),
      borderRadius: 10,
      backgroundColor: theme?.colors?.GRAY_800,
      justifyContent: 'center',
      alignItems: 'center',
    },
    eventDetail: {
      flex: 1,
      paddingLeft: 10,
    },
    eventDateTxt1: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
      textTransform: 'uppercase',
    },
    eventDateTxt2: {
      ...STYLES.textStyle(18, theme?.colors?.GRAY_300, 'BOLD'),
      marginTop: 3,
    },
    eventTitle2: {
      ...STYLES.textStyle(12, theme?.colors?.GRAY_50, 'BASE'),
    },
    eventSubjectTxt: {
      ...STYLES.textStyle(11, theme?.colors?.GRAY_200, 'BASE'),
      marginTop: 3,
    },
    eventDate: {
      ...STYLES.textStyle(11, theme?.colors?.GRAY_200, 'BASE'),
      marginTop: 3,
    },
    swipeRightIcon: {
      fontSize: 23,
      // alignSelf: 'flex-end',
      // color: 'red',
      // marginBottom: Responsive.getWidth(5.5),
    },
    swipeIcons: {
      fontSize: Responsive.getWidth(5),
      color: theme?.colors?.GRAY_50,
      // alignSelf: 'flex-end',
      // color: 'red',
      // ...COMMON_STYLE.imageStyle(6),
      // marginBottom: Responsive.getWidth(5.5),
    },
    groupWipeoutBtnViewRight: {
      backgroundColor: theme?.colors?.INPUT_BG,
      alignSelf: 'flex-end',
      width: '100%',
      height: Responsive.getWidth(10),
      marginBottom: Responsive.getWidth(5.5),
      justifyContent: 'center',
      alignItems: 'center',
    },
    groupWipeoutBtnViewLeft: {
      backgroundColor: theme?.colors?.INPUT_BG,
      alignSelf: 'flex-end',
      width: '100%',
      height: Responsive.getWidth(10),
      marginBottom: Responsive.getWidth(5),
      justifyContent: 'center',
      alignItems: 'center',
    },
    radiusRight: {
      borderTopRightRadius: 10,
      borderBottomRightRadius: 10,
    },
    radiusLeft: {
      borderTopLeftRadius: 10,
      borderBottomLeftRadius: 10,
    },
  });
